### ISSUE TITLE
What are the version of  python and pytorch?Thank you!

### ISSUE THREAD

**Issue by 4Statistics** [stes/torch-associative#2]
What are the version of  python and pytorch?Thank you very much!
because I met a lot of errors.

**Comment by stes** [comment]
Tested on `0.4.0`. Please give more details about your system setup and the error message if that does not resolve the issue. In any case, also consider using the [salad](http://salad.domainadaptation.org) library directly: https://github.com/domainadaptation/salad

**Comment by 4Statistics** [comment]
I run the program on an Ubuntu platform with python 3.6 and pytorch 0.4.0.

The erros are shown below.Thank you very much.
############
Start Experiments
Normalize data
Traceback (most recent call last):
  File "scripts/train_digits.py", line 101, in <module>
    loader_plain   = DigitsLoader('/tmp/data', dataset_names, download=True, shuffle=True, batch_size=128, normalize=True, num_workers=4)
  File "/media/sward/_lyh1/new201810171/salad-master/salad/datasets/da/digits.py", line 63, in __init__
    T.transforms.append(transforms.Normalize(*default_normalization(key)))
  File "/media/sward/_lyh1/new201810171/salad-master/salad/datasets/transforms/digits.py", line 10, in default_normalization
    'mnist': (      tensor([ 0.1309,  0.1309,  0.1309]),
TypeError: 'module' object is not callable
#####################

**Comment by 4Statistics** [comment]
I use python3.6 and Pytorch 0.4.1.
I ran the program by "Python3.6 train.py".
The error is show below.
#####
RuntimeError: CUDA error: out of memory
#######
Thank you very much.

**Comment by stes** [comment]
@4Statistics , try to decrese the batch size, e.g. using

``` bash
Python3.6 train.py --sourcebatch 20 --targetbatch 200
```

The default values are 100 and 1000, respectively, see https://github.com/stes/torch-associative/blob/cb66aef1d2296e54e09f6f970b775d5fd677601a/train.py#L30-L31

Let me know if this fixes the issue.

**Comment by mrsempress** [comment]
I just run your problem, but get an error like:
![image](https://user-images.githubusercontent.com/31315255/61761899-c3397100-ae02-11e9-9700-a409821738c7.png)
Did I ignore something?

**Comment by mrsempress** [comment]
And if set "Python3.6 train.py --sourcebatch 20 --targetbatch 200", the result looks like overfitting.
